name: Cypress Tests

on: [push] # This triggers the workflow on every push

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]  # Runs tests in parallel using 2 containers

    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Checkout your code

      - name: Cypress run
        uses: cypress-io/github-action@v6  # Use the official Cypress GitHub Action
        with:
          start: npm start  # Starts the web server for your tests
          wait-on: 'http://localhost:3000'  # Wait for the server to be available
          record: true  # Records the test results in Cypress Cloud
          parallel: true  # Run tests in parallel (split across containers)
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}  # Record key for Cypress Cloud
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token for authentication
